[package]
name = "test-service"
version = "0.1.0"
edition = "2021"

[dependencies]
jam-pvm-common = { version = "0.1.12", default-features = false, features = ["service"] }
jam-types = { version = "0.1.12", default-features = false }
polkavm-derive = "0.19.0"
